### PR TITLE
Modernize addon

### PR DESCRIPTION
**Pull request by mydea**
I initially set out to update some aspects of this addon, but after updating ember-cli etc. to latest I ended up having so many small issues that I made an all-around modernization effort instead:

* Update all dependencies, running `npx ember-cli-update`
  * This includes setting up prettier
  * This changes the support matrix to 3.16+
* Drop ember-get-config dependency (not used)
* Update ember data models/serializer/adapter to use native classes & decorators
* Update ember-cli-mirage & config a bit
* Update the dummy app to Octane paradigms
* Add acceptance tests to get a basic coverage of the models/adapter/serializer functionality
* Use `htmlSafe()` for rendered transform instead of requiring triple curlies to render it
* Replace travis with Github Actions for tests

### CODE REVIEW

**Comment by oskarrough** [comment]
Wow, thank you so much. Is there anything specific you'd like feedback on? Otherwise I'd be happy to merge.

**Comment by mydea** [comment]
I guess if you have an app at hand that you could try this out it would be nice, I tried it in our app (which has a fairly simple usage of the wordpress API) where it worked nicely.

It _should_ be (mostly??) a drop-in update, but should be a major release due to compatibility changes in the dependencies as well as potentially subtle changes in the Ember.Object --> ES6 classes migration.

**Comment by charlesfries** [comment]
Anything I can do to help get this merged in?

**Comment by oskarrough** [comment]
@mydea thanks again!
@charlesfries yes, write a comment like you did.

**Comment by charlesfries** [comment]
Any chance you could cut a release in the new future as well? Thank you!

**Comment by oskarrough** [comment]
@charlesfries here we go, 0.3.0 https://www.npmjs.com/package/ember-wordpress

**Comment by charlesfries** [comment]
Thanks!!

**Pull request merged**
