### PR TITLE
Use ember-fetch in place of ember-ajax

### PR DESCRIPTION
**Pull request by nanaewusi**

### CODE REVIEW

**Comment by MartinMalinda** [comment]
As far as I know this will have no effect. Ember data has own logic for making ajax requests and ember-ajax is a devDependency and therefore will have no impact on the parent application.

**Comment by oskarrough** [comment]
Thank you @nanaewusi.

@MartinMalinda ah really. In that case can we just remove ember-ajax? I see there's still some discussion as to what to use for Ember Data. https://github.com/emberjs/data/issues/4929

**Comment by MartinMalinda** [comment]
@oskarrough 
We can remove it, but because it is a devDepedency it will have no effect on the parent application.

**Comment by nanaewusi** [comment]
@MartinMalinda Oh. Thanks for the clarification.

**Pull request closed without merging**
